---
plugin: eigenstate.ipa.idm
server: idm.example.com
ipaadmin_principal: svc-ansible-runner

sources:
  - hosts
  - hbacrules

hbacrule_filter:
  - blastwall-ssh

host_filter_from_groups: true

hostvars_include:
  - idm_fqdn
  - idm_description
  - idm_os
  - idm_hostgroups

compose:
  ansible_host: idm_fqdn

groups:
  blastwall_policy_current: >-
    idm_description is defined and
    'bw_rpm=blastwall-selinux-0.5.2-1' in idm_description and
    'bw_state=active' in idm_description and
    'bw_alg=deny' in idm_description and
    'bw_bpf=deny' in idm_description and
    'bw_self=deny' in idm_description and
    'bw_pkt=deny' in idm_description and
    'bw_userns=deny' in idm_description and
    'bw_iou=deny' in idm_description and
    'bw_xfrm=deny' in idm_description and
    'bw_rxrpc=deny' in idm_description
  blastwall_policy_stale: >-
    idm_description is not defined or
    'bw_rpm=blastwall-selinux-0.5.2-1' not in idm_description or
    'bw_state=active' not in idm_description or
    'bw_alg=deny' not in idm_description or
    'bw_bpf=deny' not in idm_description or
    'bw_self=deny' not in idm_description or
    'bw_pkt=deny' not in idm_description or
    'bw_userns=deny' not in idm_description or
    'bw_iou=deny' not in idm_description or
    'bw_xfrm=deny' not in idm_description or
    'bw_rxrpc=deny' not in idm_description
  blastwall_policy_candidate: >-
    idm_description is not defined or
    'bw_rpm=blastwall-selinux-0.5.2-1' not in idm_description or
    'bw_state=active' not in idm_description or
    'bw_alg=deny' not in idm_description or
    'bw_bpf=deny' not in idm_description or
    'bw_self=deny' not in idm_description or
    'bw_pkt=deny' not in idm_description or
    'bw_userns=deny' not in idm_description or
    'bw_iou=deny' not in idm_description or
    'bw_xfrm=deny' not in idm_description or
    'bw_rxrpc=deny' not in idm_description
