apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 05-workload-namespace.yaml
  - 10-rawselinuxprofile-blastwall.yaml
  - 11-rawselinuxprofile-blastwall-nested.yaml
  - 20-scc-blastwall-confined.yaml
  - 30-workload-rbac.yaml
  - 40-test-harness-configmap.yaml
