---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:105ad5c7c5f7b5c4c5ac5478fcdf5de4b5b66d91bb15fa0bc926a4b7da329847

dependencies:
  galaxy: requirements.yml
  system: bindep.txt
  python: python-requirements.txt

additional_build_steps:
  append_final:
    - RUN mkdir -p /etc/ipa && chgrp -R 0 /etc/ipa && chmod -R g+rwX /etc/ipa
